version: '3.8'
services:
  # 1. Servis: Bizim Node.js Uygulamamız
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/hrms-api-db
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
    depends_on:
      # DÜZELTME: Artık sadece servislerin başlamasını değil,
      # "sağlıklı" olmalarını bekliyoruz.
      mongo:
        condition: service_started # MongoDB için başlangıç yeterli
      redis:
        condition: service_healthy # Redis için sağlıklı olmasını bekle!

  # 2. Servis: MongoDB Veritabanı
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 3. Servis: Redis Hafıza Veritabanı
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    # YENİ EKLENEN KISIM: SAĞLIK KONTROLÜ
    healthcheck:
      # Redis'in hazır olup olmadığını anlamak için 'redis-cli ping' komutunu kullan.
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s # Her 10 saniyede bir kontrol et
      timeout: 5s   # Cevap için 5 saniye bekle
      retries: 5    # 5 kere başarısız olursa sağlıksız kabul et

volumes:
  mongo-data:
