version: '3.8'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/hrms-api-db
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  k6:
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ./stress-test.js:/tests/stress-test.js
    depends_on:
      app:
        condition: service_healthy
volumes:
  mongo-data:
